### ISSUE TITLE
incomplete error message

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold-score#33]
```
RuntimeError: Host "No" is in a wrong format
    /home/r/.ruby/gems/zold-score-0.4.4/lib/zold/score.rb:67:in `initialize'
    /home/r/.ruby/gems/zold-score-0.4.4/lib/zold/score.rb:164:in `new'
    /home/r/.ruby/gems/zold-score-0.4.4/lib/zold/score.rb:164:in `parse'
    /home/r/repo/lib/zold/node/farmers.rb:129:in `block in up'
    /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/open3.rb:219:in `popen_run'
    /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/open3.rb:208:in `popen2e'
    /home/r/repo/lib/zold/node/farmers.rb:102:in `up'
    /home/r/repo/test/node/test_farmers.rb:42:in `block in test_calculates_next_score'
    /home/r/repo/test/node/test_farmers.rb:40:in `each'
    /home/r/repo/test/node/test_farmers.rb:40:in `test_calculates_next_score'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.5`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold-score#33` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
